[package]
name = "crabby-merge"
version = "0.1.0"
authors = ["Kesavan Yogeswaran <kesyog@gmail.com>"]
edition = "2018"

[profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow = "^1.0"
# TODO: remove and access environment variables directly
dotenv = { version = "^0.15.0" }
futures = "^0.3.5"
lazy_static = "^1.4.0"
log = "^0.4"
regex = "^1.3"
reqwest = { version = "^0.10", default-features = false, features = ["rustls-tls"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
simple_logger = "^1"
tokio = { version = "^0.2", features = ["rt-threaded", "macros", "sync"] }
url = "^2.1.1"
