[package]
name = "crabby-merge"
version = "0.2.1"
authors = ["Kesavan Yogeswaran <kesyog@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/kesyog/crabby-merge"
repository = "https://github.com/kesyog/crabby-merge"

[profile.release]
lto = "thin"
# codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1"
config = { version = "0.11", default-features = false, features = ["toml"] }
dirs = "3.0"
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simple_logger = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
url = "2.2"
