[package]
name = "crabby-merge"
version = "0.2.0"
authors = ["Kesavan Yogeswaran <kesyog@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Unlicense"
homepage = "https://github.com/kesyog/crabby-merge"
repository = "https://github.com/kesyog/crabby-merge"

[profile.release]
lto = "thin"
# codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "^1.0"
config = { version = "^0.10.1", default-features = false, features = ["toml"] }
dirs = "^3.0.1"
futures = "^0.3.5"
lazy_static = "^1.4.0"
log = "^0.4"
regex = "^1.3"
reqwest = { version = "^0.10", default-features = false, features = ["rustls-tls"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
simple_logger = "^1"
tokio = { version = "^0.2", features = ["rt-core", "macros"] }
url = "^2.1.1"
